[package]
name = "rust-bio-bench"
version = "0.1.0"
authors = ["Yishen Miao <mys721tx@gmail.com>"]
edition = "2018"

[dependencies]
bio = "0.28"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "reader"
harness = false
